name: AMC CI | Manage Workflows

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Get updated code from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Fetch depth is necessary that you specify the fetch-depth argument to actions/checkout@v2 step. By default they fetch only latest commit of the branch, but we need more commits since we validate a range of commit messages.

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test:ci

      - name: Run ESLint
        run: yarn lint

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v4

      - name: Generate coverage reports with Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.UPLOAD_TOKEN }} # not required for public repos
          # files: ./coverage1.xml,./coverage2.xml # optional
          # flags: unittests # optional
          name: Codecov checking # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  deploy:
    needs: release
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: deploy to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN || github.token }} # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          # vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
