name: AMC CI | Deploy

on:
  workflow_call:

jobs:
  release:
    uses: ./.github/workflows/amc-release.yml
  deploy:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: deploy to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN || github.token }} # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          # vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
