name: AMC CI | Build

on:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Get updated code from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Fetch depth is necessary that you specify the fetch-depth argument to actions/checkout@v2 step. By default they fetch only latest commit of the branch, but we need more commits since we validate a range of commit messages.

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test:ci

      - name: Run ESLint
        run: yarn lint

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v4

      - name: Generate coverage reports with Codecov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.UPLOAD_TOKEN }} # not required for public repos
          # files: ./coverage1.xml,./coverage2.xml # optional
          # flags: unittests # optional
          name: Codecov checking # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

